version: '3'
services:
  driver:
    image: jeguzzi/robomaster_ros:galactic
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: host
    command: ros2 launch robomaster_ros ep.launch name:=rm_ep /rm_ep/imu:=/testing conn_type:="rndis"
    environment:
      - ROS_DOMAIN_ID=120
    stdin_open: true 
    tty: true
  teleop:
    privileged: true
    image: jeguzzi/robomaster_ros:galactic
    network_mode: host
    command: ros2 launch robomaster_ros teleop.launch model:=ep name:=rm_ep conn_type:="rndis"
    environment:
      - ROS_DOMAIN_ID=120
